### ISSUE TITLE
블루투포스 이름정정

### ISSUE THREAD

**Issue by axisotherwise** [unchaptered/hanghae-algorithm-study#19]
![image](https://user-images.githubusercontent.com/94421127/180232915-8fcb9c27-6b3d-4ffd-8860-378cddd69ad8.png)  
https://namu.wiki/w/%EB%B8%8C%EB%A3%A8%ED%8A%B8%20%ED%8F%AC%EC%8A%A4  

블루투포스의 정확한 이름은 브루트 포스라고 합니다.

**Comment by unchaptered** [comment]
감사합니다! 바로 반영하겠습니다 ✅
